---
- hosts: all
  become: yes
  become_user: postgres
  vars:
    pgdd: "{{ ansible_env.HOME }}/{{ pgver }}/data"

  tasks:
  
  - lineinfile: dest="{{ ansible_env.HOME }}/.bash_profile" line="export PATH=$PATH:/usr/pgsql-{{ pgver }}/bin"
 
  - name: Postgres Initdb
    shell: source {{ ansible_env.HOME }}/.bash_profile && test -d {{ pgdd  }} || initdb -D {{ pgdd }}

  - replace: dest={{ pgdd }}/postgresql.conf regexp='#*(unix_socket_directories *= *).*' replace="\1'/tmp'"
  - replace: dest={{ pgdd }}/postgresql.conf regexp='#*(listen_addresses *= *).*' replace="\1'*'"
  - replace: dest={{ pgdd }}/postgresql.conf regexp='#*(log_destination *= *).*' replace="\1'csvlog'"
  - lineinfile: dest={{ pgdd }}/pg_hba.conf  line="host    all             all             all                     trust"

  - name: Starting PostgreSQL
    shell: source {{ ansible_env.HOME }}/.bash_profile && pg_ctl -D {{ pgdd }} start
