---
- hosts: all
  become: yes
  
  tasks:

  - name: Adding PGDG Repo
    yum_repository:
       name: pgdg-{{ pgver }}
       description: pgdg-{{ pgver }}
       baseurl: ftp://ftp.mirrors.postgresql.org/pub/repos/yum/{{ pgver }}/redhat/rhel-$releasever-$basearch
       gpgcheck: no
       enabled: yes

  - name: Installing Packages 
    yum: name="{{ item  }}" state=present
    with_items:
       - "{{ packages }}"

  - include: install_pip.yml
